language: node_js
node_js:
  - lts/dubnium
  - node
sudo: false
after_script: bash <(curl -s https://codecov.io/bash)
deploy:
  - provider: releases
    skip_cleanup: true
    api_key:
      secure: abjmDo2hhoFo4QZzJNIzvAqLDeB+1cPq3Gvi0hlA08GrUpExBhCHf2CRCt/oXw9rcCvMTyPwUvRWdpWbM1MCNvVVPuFmVx3H7TSCDgGCuq9ux1mNSfDSu5DLYnOu7SXiNwGno+vk1LFGPJ1xPY8YxKfl/ApgkJQQDLcdChp62W8=
    file:
      - 'gemoji.js'
      - 'gemoji.min.js'
    on:
      tags: true
