language: node_js
node_js:
- lts/boron
- node
sudo: false
after_script: bash <(curl -s https://codecov.io/bash)
deploy:
  - provider: releases
    skip_cleanup: true
    api_key:
      secure: FxpovIE7QobbxBS0Rm6AsoHzVC5uYtuwKly/2SMZD19ff78A+XLoH971jLSAvx0PTul5nNy26drDVTRlgXZznM1DISdJXOEFQhR2O2CpEEFhHxKt/kixndFWfOBxrbH3534CLuTzV1AwXQvC5WE7y7in0zu/E9/ZdC3CA7ux1h8=
    file:
      - "gemoji.js"
      - "gemoji.min.js"
    on:
      tags: true
